### ISSUE TITLE
Improve pagespeed

### ISSUE THREAD

**Issue by gordcorp** [AusDTO/dta-website#207]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.dta.gov.au%2F&tab=mobile
58/100 could be better

**Comment by bjgordon** [comment]
Have combined js files in #208 so there is now only one blocking js file, however the score is still pretty low at 61 / 100

**Comment by bjgordon** [comment]
Turns out the ui-kit js can't be loaded via async, so had to revert. Back to 58/100 :-(

**Comment by bjgordon** [comment]
Things to try next:
1. Optimise images in the build pipeline.
2. Load index.json on the search page only, not on every page
