### ISSUE TITLE
Add a test for trailing slash in permalink frontmatter

### ISSUE THREAD

**Issue by gordcorp** [AusDTO/dta-website#216]
A content author had an issue where they neglected a trailing slash in a page's permalink i.e. /foo. Links to /foo were then failing in htmlproofer, and it wasn't clear what was wrong. Since /foo pages don't get served by nginx unless the user visits /foo.html, all page permalinks have a trailing slash. It seems the best way is to add a test which fails if a permalink is missing a trailing slash. This would be clearer for content authors by pinpointing the permalink line as having the error, not the link.

**Comment by bjgordon** [comment]
Possibly https://github.com/18F/jekyll_frontmatter_tests will include this and other useful tests

**Comment by bjgordon** [comment]
Actually I found that nginx may be able to be configured to work without the trailing slash: https://jekyllrb.com/docs/permalinks/#nginx This would probably be a better solution.

**Comment by bjgordon** [comment]
Tested it out by adding `try_files $uri $uri.html $uri/ =404;` to nginx.conf to the bottom of `location / {`, and adding a page with permalink: /foo.
/foo was then accessible at /foo and /foo.html. 
Trying /foo/ gave a 404.
However, internal links to this page had to use /foo.html to prevent htmlproofer's LinkCheck failing. Wasn't able to fix htmlproofer, so it's probably best to keep requiring trailing slashes.
