### ISSUE TITLE
Update content on DSS referring to "design or redesign" in 2016

### ISSUE THREAD

**Issue by jonathanconway** [AusDTO/dta-website#260]
> The Standard is now live and services will be assessed if design or redesign commences after 6 May 2016.

(https://www.dta.gov.au/standard/)

The copy here could be updated, at the very least to refer to the May 2016 date in past-tense.

**Comment by Phend-117** [comment]
Thanks @jonathanconway. We've got a bunch of content work on our backlog, and I will add this.

**Comment by skpandey27** [comment]
Done.
