### ISSUE TITLE
[19] Links are not visually identifiable

### ISSUE THREAD

**Issue by bjgordon** [AusDTO/dta-website#292]

**Comment by bjgordon** [comment]
The main need to show the URL is when the page is printed, we want to show the url somewhere. Ideally uikit would provide a print stylesheet for this, but in Chrome and Safari mac osx when the page is printed the links are appended after the link text. Thus we actually dont need to show the URL on the page. Let's just remove it.

**Comment by skpandey27** [comment]
Link url is removed from search page.
