### ISSUE TITLE
Add <meta> author tag

### ISSUE THREAD

**Issue by bjgordon** [AusDTO/dta-website#317]
As an example, if shared in Facebook this will show the author name as part of the post preview

**Comment by elisechant** [comment]
yeah, og tags for Facebook as well as the standard meta ones

**Comment by bjgordon** [comment]
It'd be easiest if we could just use [a jekyll plugin](https://github.com/jekyll/jekyll-seo-tag), but I didn't find one compatible with jekyll-assets, so our current tagging was hand coded in.  I might look into that again though...
