### ISSUE TITLE
New posts sometimes show not found

### ISSUE THREAD

**Issue by gordcorp** [AusDTO/dta-website#370]
When a new post is published to prod, it will show on the front page immediately, but clicking on the link to the post sometimes gives a page not found. It usually resolves itself within a few minutes, so may be a caching issue with cloud front.

**Comment by bjgordon** [comment]
Have tweaked the cache length a little to see if it helps. https://github.com/AusDTO/dta-website/commit/3ce8cbb03462ca1fc7eb1af02ccab997a0bf310d
