### ISSUE TITLE
Archive and redirect writing and accessibility DTA Guides to Content Guide

### ISSUE THREAD

**Issue by joolswood** [AusDTO/dta-website#433]
We can now archive and redirect traffic from these guides:

- [ ]  https://www.dta.gov.au/standard/design-guides/inclusive-services/ goes to https://guides.service.gov.au/content-guide/accessibility-inclusivity/
- [ ]  https://www.dta.gov.au/standard/design-guides/testing-web-accessibility/ goes to https://guides.service.gov.au/content-guide/accessibility-inclusivity/
- [ ]  https://www.dta.gov.au/standard/design-guides/making-content-accessible/ goes to https://guides.service.gov.au/content-guide/accessibility-inclusivity/
- [ ]  https://www.dta.gov.au/standard/design-guides/online-writing/ goes to https://guides.service.gov.au/content-guide/

Also remove the links from the index page https://www.dta.gov.au/standard/design-guides/

Let me know if you have questions.

Thanks!

**Comment by skpandey27** [comment]
All done.
