### ISSUE TITLE
policy@digital.gov.au bouncing

### ISSUE THREAD

**Issue by svict4** [AusDTO/dta-website#645]
Tried to get in contact with policy@digital.gov.au from the [contact page](https://github.com/AusDTO/dta-website/blob/2555f2c5ac500cddb678729e936016955d0adfcb/pages/contact/contact.md) but appears to no longer exist. Does someone have an updated address?

**Comment by imperator99** [comment]
Hey Simon thanks for letting us know. I'll check into it.

**Comment by imperator99** [comment]
Hey Simon. Please email [DTAcomms@digital.gov.au](mailto:DTAcomms@digital.gov.au) and someone will get back to you. Apologies for the inconvenience and thanks for letting us know.
